// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemadeRamais.Data;

namespace SistemadeRamais.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemadeRamais.Models.CadastroModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COLABORADOR_VC_RAMAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILIAL_VC_RAMAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAMAL_CH_RAMAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SETOR_VC_RAMAL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TAB_RAMAIS");
                });
#pragma warning restore 612, 618
        }
    }
}
